`️️️️ㅤ⚡️ BUMP ⚡️ㅤ` `ㅤabuseipdb-check ↑12 ↓6ㅤ`

diff --git a/bin/abuseipdb-check b/bin/abuseipdb-check
--- a/bin/abuseipdb-check
+++ b/bin/abuseipdb-check
@@ -6,19 +6,25 @@ if [ -z "$ABUSEIPDB_TOKEN" ]; then
 fi
 
 if [ -z "$1" ]; then
-  echo "Error: No IP or subnet provided."
-  exit 1
+  if [ -t 0 ]; then
+    echo "Error: No IP or subnet provided."
+    exit 1
+  else
+    IP=$(cat)
+  fi
+else
+  IP="$1"
 fi
 
-# Strip whitespace and unwanted characters from the first argument
-IP=$(echo "$1" | sed 's/[^0-9./]//g')
+# Strip whitespace and unwanted characters
+IP=$(echo "$IP" | sed 's/[^0-9./]//g')
 
 function check-block() {
   local SUBNET="$1"
   bkt --ttl=1d -- \
     curl -sG https://api.abuseipdb.com/api/v2/check-block \
     --data-urlencode "network=$SUBNET" \
-    -d maxAgeInDays=7 \
+    -d maxAgeInDays=30 \
     -H "Key: $ABUSEIPDB_TOKEN" \
     -H "Accept: application/json" | \
     jq '.data.reportedAddress'
@@ -28,7 +34,7 @@ function check() {
   local IP="$1"
   bkt --ttl=1d -- curl -sG https://api.abuseipdb.com/api/v2/check \
     --data-urlencode "ipAddress=$IP" \
-    -d maxAgeInDays=7 \
+    -d maxAgeInDays=30 \
     -d verbose \
     -H "Key: $ABUSEIPDB_TOKEN" \
     -H "Accept: application/json" | \
