bump

diff --git a/bin/dot-eget b/bin/dot-eget
--- a/bin/dot-eget
+++ b/bin/dot-eget
@@ -3,7 +3,7 @@
 mkdir -p ~/.local/bin
 
 ip=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}')
-echo $ip | grep '10.0.100.' > /dev/null || { echo "Sorry, WIFI is required" && exit 1; }
+echo $ip | egrep '^10\.0\.' > /dev/null || { echo "Sorry, WIFI is required" && exit 1; }
 
 
 
@@ -33,6 +33,7 @@ dl 1w https://github.com/mergestat/mergestat-lite
 dl 1d https://github.com/s0rg/crawley
 dl 1d https://github.com/dimo414/bkt
 dl 1w https://github.com/Inlyne-Project/inlyne            # a GPU powered yet browserless tool to help you quickly view markdown files in the blink of an eye.
+dl 1w https://github.com/Inlyne-Project/inlyne            # a GPU powered yet browserless tool to help you quickly view markdown files in the blink of an eye.
 dl 1w https://github.com/kurtbuilds/checkexec             # Conditionally run a command in a CLI (like Make, as a standalone tool)
 dl 1d https://github.com/dundee/gdu --to=gdu
 dl 1w https://github.com/ismaelgv/rnr
@@ -56,6 +57,10 @@ dl 1w https://github.com/extrawurst/gitui
 dl 1w https://github.com/mgdm/htmlq
 dl 1w https://github.com/sharkdp/hyperfine
 dl 1w https://github.com/sibprogrammer/xq
+dl 1w https://github.com/zhanhb/cidr-merger
+
+# Syntax-highlighting pager for git and diff output
+dl 1w https://github.com/dandavison/delta
 
 # A command-line tool to select default applications for document types and URL schemes on Mac OS X
 dl 1w https://github.com/moretension/duti
@@ -70,7 +75,8 @@ dl 1w $(bkt --ttl=24h -- crawley -silent https://evermeet.cx/pub/ffmpeg/ | grep 
 dl 1w $(bkt --ttl=24h -- crawley -silent https://evermeet.cx/pub/ffprobe/ | grep .zip$ | head -1)
 
 # Completions
-bkt --ttl=2d -- just --completions zsh >| /opt/homebrew/share/zsh/site-functions/_just
+bkt --ttl=2d -- just --completions zsh >| $HOME/.local/share/zsh/site-functions/_just
+bkt --ttl=2d -- netbird completion zsh >| $HOME/.local/share/zsh/site-functions/_netbird
 
 # wait
 
