`️️️️ㅤ⚡️ BUMP ⚡️ㅤ` `ㅤ16 files ↑171 ↓39ㅤ`

diff --git a/bin/pstats b/bin/pstats
--- a/bin/pstats
+++ b/bin/pstats
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
-
 # Inspired from this blog article : http://www.thegeekstuff.com/2013/10/time-command-format/
+
+command -v ets >/dev/null 2>&1 || {
+  echo "ets command not found. Please install it first."
+  exit 1
+}
 
 if [[ ! -z "${CI}" ]]; then
   # Github Actions color works in mysterious ways ...
@@ -20,7 +24,7 @@ FILE=$(mktemp)
 time=$(command -v gtime || command -v /usr/bin/time)
 grep=$(command -v ggrep || command -v /usr/bin/grep)
 
-$time -o $FILE -f "       Total $BAR %es  [%P  %MK  %I/%O]" ets -s -f "%Mm  %S.%Ls $BAR" -- "$@"
+$time -o $FILE -f "       Total $BAR %es  [%P  %MK  %I/%O]" ets -s -f "%Mm  %S.%Ls $BAR" 2> /dev/null -- "$@"
 code=$?
 
 echo "             $BAR"
